
line-length = 120
target-version = "py311"

# Exclude directories
exclude = [
  "__pycache__",
  "external",
  ".git",
  ".venv",
  ".pytest_cache",
  ".ruff_cache",
  ".pyright",
  ".pyright_cache",
  "typings",
  "node_modules",
]

[format]
quote-style = "double"

[lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # import sorting
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
  "N",   # pep8-naming
  "A",   # flake8-builtins
  "C4",  # flake8-comprehensions
  "DTZ", # datetime-timezone
  "PL",  # pylint-inspired checks
  "PIE"  # flake8-pie
]
ignore = [
  "E203",      # keep black compatibility
  "PLR0913"    # allow functions with many args (adjust as needed)
]
fixable = ["ALL"]

[lint.isort]
combine-as-imports = true
known-first-party = ["pipeline", "models"]

[lint.per-file-ignores]
# Allow lazy imports (optional dependencies) in these modules
"models/doclayout_yolo.py" = ["PLC0415"]
"pipeline/layout/detection/doclayout_yolo.py" = ["PLC0415"]
"pipeline/layout/detection/mineru/*.py" = ["PLC0415"]
"pipeline/layout/ordering/mineru/*.py" = ["PLC0415"]
"pipeline/layout/ordering/olmocr/*.py" = ["PLC0415"]
"pipeline/layout/ordering/pymupdf/*.py" = ["PLC0415"]
# Test files: allow magic numbers (concrete test values)
"tests/test_*.py" = ["PLR2004"]
