
line-length = 120
target-version = "py311"

[format]
quote-style = "double"

[lint]
select = ["E", "F", "I"]
ignore = ["E203"]

[lint.isort]
combine-as-imports = true
known-first-party = ["pipeline", "models"]
